env: "local"                          # local dev prod
storag_path: "./storage/storage.go"
http_server: 
  address: "localhost:8082"
  timeout: 4s                         # время для чтения запроса и отправки ответа
  idle_timeout: 60s                   # время жизни соединения с клиентом 